@Resume.API_HostAddress = https://localhost:7210

POST {{Resume.API_HostAddress}}/AddPerson/
Accept: application/json

###

POST {{Resume.API_HostAddress}}/AddJob/
Accept: application/json

###

GET {{Resume.API_HostAddress}}/ListPerson/
Accept: application/json

###

GET {{Resume.API_HostAddress}}/GetPersonJobBetweenDates/
Accept: application/json